baseURL: http://globalgov.ch
publishDir: docs
languageCode: en-us
title: Geneva Global Governance Observatory
theme: roxo-hugo
summarylength: 25
menu:
  nav:
    - name: Home
      url: ''
      weight: 1
    - name: About
      url: about
      weight: 2
    - name: Data
      url: portfolio
      weight: 3
    - name: Blog
      url: blog
      weight: 4
    - name: Get in touch
      url: contact
      weight: 5
params:
  author: GLOBALGOV
  banner:
    background_image: images/backgrounds/network2.jpg 
    enable: yes
    heading: Geneva Global Governance Observatory
    primary_button: Blog posts
    primary_button_url: blog
    secondary_button: GGO Data
    secondary_button_url: portfolio
  blog:
    read_more: read more
  portfolio:
    enable: yes
    title: GGO Data
    subtitle: Need Gobal Governance Data?
    view_project: View data
    more_works: More data
    scroll_down: scroll down
  call_to_action:
    background_image: images/backgrounds/cta-background.jpg
    enable: yes
    primary_button: Submit Query
    primary_button_url: contact
    secondary_button: Not Convinced
    secondary_button_url: portfolio
    title: Get in touch with us!
  contactForm:
    placeholder_about_the_project: Message
    placeholder_email: Email
    placeholder_first_name: First Name
    placeholder_last_name: Last Name
    send_message: Send Message
  dateFormat: 26 FEB 1994
  description: The largest repository of Global Governance Data
  fabform: https://fabform.io/f/USAg2Jl
  footer:
    contactInfo:
      email: info@globalgov.ch
      title: Contact Info
    service:
      description: 'We develop and maintain ‘many’ packages containing data on actors and institutions of global governance!'
      title: Providing data across various issue domains of Global Governance
    sitemap:
      link:
        - name: About
          url: about
        - name: Data
          url: portfolio
        - name: Blog
          url: blog
        - name: Contact
          url: contact
      title: Sitemap
    # social:
    #   link:
    #     - name: Medium
    #       url: '#'
    #     - name: Behance
    #       url: '#'
    #     - name: Dribbble
    #       url: '#'
    #     - name: Instagram
    #       url: '#'
    #   title: Social Media
  #googleAnalitycsID: Your ID
  logo: images/logo.png
  navAction:
    name: Get in touch
    status: yes
    url: contact

markup:
  goldmark:
    renderer:
      unsafe: true
